version: '3.7'
networks: 
  basic-net:
    driver: bridge
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-basic-crud
    ports: 
      - "8000:80"
    volumes: 
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - basic-net
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-basic-net
    restart: unless-stopped
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - basic-net
  php:
    build: 
      context: .
      dockerfile: app.Dockerfile
    container_name: php-basic-crud
    volumes: 
      - ./:/var/www
    ports: 
      - 5001:80
    depends_on: 
      - mysql
    networks: 
      - basic-net
  
